
[theme]
base="dark"
primaryColor="#642ed1"

# Background color for the main content area
backgroundColor ="#f2f3f5"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#d5d9e6'

# Color used for almost all text
textColor = '#010311'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"